# Use an official PHP runtime as a parent image
FROM php:latest
# Set the working directory to /var/www/html
WORKDIR /var/www/html
# Copy the contents of the current directory into the container at /var/www/html
COPY . /var/www/html
# Expose port 80
EXPOSE 80
CMD ["php", "-S", "0.0.0.0:80"]